version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/hritikranjan/Documents/Code/postgresData/PFH:/var/lib/postgresql/data
      - ./src/db/migrations/sql:/docker-entrypoint-initdb.d
